# Generated by Django 4.0 on 2025-01-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Tollstation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('road', models.CharField(blank=True, max_length=200, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('price1', models.FloatField(blank=True, null=True)),
                ('price2', models.FloatField(blank=True, null=True)),
                ('price3', models.FloatField(blank=True, null=True)),
                ('price4', models.FloatField(blank=True, null=True)),
                ('tollid', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbconnect.operator')),
            ],
            options={
                'db_table': 'tollstation',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagref', models.CharField(blank=True, db_column='tagRef', max_length=200, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbconnect.operator')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(blank=True, max_length=200, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbconnect.tag')),
                ('tollstation', models.ForeignKey(blank=True, db_column='tollStation_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dbconnect.tollstation')),
            ],
            options={
                'db_table': 'pass',
            },
        ),
    ]
