# Generated by Django 4.2 on 2025-01-25 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbconnect.tag'),
        ),
    ]
