# Generated by Django 4.2 on 2025-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnect', '0002_alter_pass_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
