# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.admin_healthcheck_get401_response import AdminHealthcheckGet401Response

class TestAdminHealthcheckGet401Response(unittest.TestCase):
    """AdminHealthcheckGet401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminHealthcheckGet401Response:
        """Test AdminHealthcheckGet401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminHealthcheckGet401Response`
        """
        model = AdminHealthcheckGet401Response()
        if include_optional:
            return AdminHealthcheckGet401Response(
                status = 'failed',
                dbconnection = ''
            )
        else:
            return AdminHealthcheckGet401Response(
        )
        """

    def testAdminHealthcheckGet401Response(self):
        """Test AdminHealthcheckGet401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
