# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.passes_cost_toll_op_id_tag_op_id_date_from_date_to_get200_response import PassesCostTollOpIDTagOpIDDateFromDateToGet200Response

class TestPassesCostTollOpIDTagOpIDDateFromDateToGet200Response(unittest.TestCase):
    """PassesCostTollOpIDTagOpIDDateFromDateToGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PassesCostTollOpIDTagOpIDDateFromDateToGet200Response:
        """Test PassesCostTollOpIDTagOpIDDateFromDateToGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PassesCostTollOpIDTagOpIDDateFromDateToGet200Response`
        """
        model = PassesCostTollOpIDTagOpIDDateFromDateToGet200Response()
        if include_optional:
            return PassesCostTollOpIDTagOpIDDateFromDateToGet200Response(
                toll_op_id = '',
                tag_op_id = '',
                request_timestamp = '2024-11-15 12:34',
                period_from = '',
                period_to = '',
                n_passes = 56,
                passes_cost = 1.337
            )
        else:
            return PassesCostTollOpIDTagOpIDDateFromDateToGet200Response(
        )
        """

    def testPassesCostTollOpIDTagOpIDDateFromDateToGet200Response(self):
        """Test PassesCostTollOpIDTagOpIDDateFromDateToGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
