# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_admin_addpasses_post(self) -> None:
        """Test case for admin_addpasses_post

        Εισαγωγή νέων διελεύσεων
        """
        pass

    def test_admin_healthcheck_get(self) -> None:
        """Test case for admin_healthcheck_get

        Έλεγχος συνδεσιμότητας συστήματος (healthcheck)
        """
        pass

    def test_admin_resetpasses_post(self) -> None:
        """Test case for admin_resetpasses_post

        Αρχικοποίηση των διελεύσεων
        """
        pass

    def test_admin_resetstations_post(self) -> None:
        """Test case for admin_resetstations_post

        Αρχικοποίηση των σταθμών διοδίων
        """
        pass

    def test_charges_by_toll_op_id_date_from_date_to_get(self) -> None:
        """Test case for charges_by_toll_op_id_date_from_date_to_get

        Διελεύσεις και χρεώσεις λοιπών λειτουργών
        """
        pass

    def test_login_post(self) -> None:
        """Test case for login_post

        Είσοδος χρήστη (login)
        """
        pass

    def test_logout_post(self) -> None:
        """Test case for logout_post

        Έξοδος χρήστη (logout)
        """
        pass

    def test_pass_analysis_station_op_id_tag_op_id_date_from_date_to_get(self) -> None:
        """Test case for pass_analysis_station_op_id_tag_op_id_date_from_date_to_get

        Ανάλυση διελεύσεων μεταξύ λειτουργών
        """
        pass

    def test_passes_cost_toll_op_id_tag_op_id_date_from_date_to_get(self) -> None:
        """Test case for passes_cost_toll_op_id_tag_op_id_date_from_date_to_get

        Κόστος διελεύσεων μεταξύ λειτουργών
        """
        pass

    def test_toll_station_passes_toll_station_id_date_from_date_to_get(self) -> None:
        """Test case for toll_station_passes_toll_station_id_date_from_date_to_get

        Λήψη διελεύσεων για σταθμό διοδίων
        """
        pass


if __name__ == '__main__':
    unittest.main()
