# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.admin_healthcheck_get200_response import AdminHealthcheckGet200Response

class TestAdminHealthcheckGet200Response(unittest.TestCase):
    """AdminHealthcheckGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdminHealthcheckGet200Response:
        """Test AdminHealthcheckGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdminHealthcheckGet200Response`
        """
        model = AdminHealthcheckGet200Response()
        if include_optional:
            return AdminHealthcheckGet200Response(
                status = 'OK',
                dbconnection = '',
                n_stations = 56,
                n_tags = 56,
                n_passes = 56
            )
        else:
            return AdminHealthcheckGet200Response(
        )
        """

    def testAdminHealthcheckGet200Response(self):
        """Test AdminHealthcheckGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
