# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.toll_station_passes_toll_station_id_date_from_date_to_get200_response_pass_list_inner import TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner

class TestTollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner(unittest.TestCase):
    """TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner:
        """Test TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner`
        """
        model = TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner()
        if include_optional:
            return TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner(
                pass_index = 56,
                pass_id = '',
                timestamp = '2024-11-15 12:34',
                tag_id = '',
                tag_provider = '',
                pass_type = 'home',
                pass_charge = 1.337
            )
        else:
            return TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner(
        )
        """

    def testTollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner(self):
        """Test TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
