# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.charges_by_toll_op_id_date_from_date_to_get200_response_vop_list_inner import ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner

class TestChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner(unittest.TestCase):
    """ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner:
        """Test ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner`
        """
        model = ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner()
        if include_optional:
            return ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner(
                visiting_op_id = '',
                n_passes = 56,
                passes_cost = 1.337
            )
        else:
            return ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner(
        )
        """

    def testChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner(self):
        """Test ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
