# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.charges_by_toll_op_id_date_from_date_to_get200_response_vop_list_inner import ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner
from typing import Optional, Set
from typing_extensions import Self

class ChargesByTollOpIDDateFromDateToGet200Response(BaseModel):
    """
    ChargesByTollOpIDDateFromDateToGet200Response
    """ # noqa: E501
    toll_op_id: Optional[StrictStr] = Field(default=None, alias="tollOpID")
    request_timestamp: Optional[StrictStr] = Field(default=None, alias="requestTimestamp")
    period_from: Optional[StrictStr] = Field(default=None, alias="periodFrom")
    period_to: Optional[StrictStr] = Field(default=None, alias="periodTo")
    v_op_list: Optional[List[ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner]] = Field(default=None, alias="vOpList")
    __properties: ClassVar[List[str]] = ["tollOpID", "requestTimestamp", "periodFrom", "periodTo", "vOpList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChargesByTollOpIDDateFromDateToGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in v_op_list (list)
        _items = []
        if self.v_op_list:
            for _item_v_op_list in self.v_op_list:
                if _item_v_op_list:
                    _items.append(_item_v_op_list.to_dict())
            _dict['vOpList'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChargesByTollOpIDDateFromDateToGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tollOpID": obj.get("tollOpID"),
            "requestTimestamp": obj.get("requestTimestamp"),
            "periodFrom": obj.get("periodFrom"),
            "periodTo": obj.get("periodTo"),
            "vOpList": [ChargesByTollOpIDDateFromDateToGet200ResponseVOpListInner.from_dict(_item) for _item in obj["vOpList"]] if obj.get("vOpList") is not None else None
        })
        return _obj


