# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PassesCostTollOpIDTagOpIDDateFromDateToGet200Response(BaseModel):
    """
    PassesCostTollOpIDTagOpIDDateFromDateToGet200Response
    """ # noqa: E501
    toll_op_id: Optional[StrictStr] = Field(default=None, alias="tollOpID")
    tag_op_id: Optional[StrictStr] = Field(default=None, alias="tagOpID")
    request_timestamp: Optional[StrictStr] = Field(default=None, alias="requestTimestamp")
    period_from: Optional[StrictStr] = Field(default=None, alias="periodFrom")
    period_to: Optional[StrictStr] = Field(default=None, alias="periodTo")
    n_passes: Optional[StrictInt] = Field(default=None, alias="nPasses")
    passes_cost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="passesCost")
    __properties: ClassVar[List[str]] = ["tollOpID", "tagOpID", "requestTimestamp", "periodFrom", "periodTo", "nPasses", "passesCost"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PassesCostTollOpIDTagOpIDDateFromDateToGet200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PassesCostTollOpIDTagOpIDDateFromDateToGet200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tollOpID": obj.get("tollOpID"),
            "tagOpID": obj.get("tagOpID"),
            "requestTimestamp": obj.get("requestTimestamp"),
            "periodFrom": obj.get("periodFrom"),
            "periodTo": obj.get("periodTo"),
            "nPasses": obj.get("nPasses"),
            "passesCost": obj.get("passesCost")
        })
        return _obj


