# coding: utf-8

"""
    Toll Management REST API

    REST API για τη διαχείριση διαλειτουργικότητας διοδίων στους αυτοκινητόδρομους. Περιέχει endpoints για login/logout, διαχείριση διαδοχών διέλευσης, αναλύσεις και διαχειριστικές λειτουργίες. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner(BaseModel):
    """
    TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner
    """ # noqa: E501
    pass_index: Optional[StrictInt] = Field(default=None, alias="passIndex")
    pass_id: Optional[StrictStr] = Field(default=None, alias="passID")
    timestamp: Optional[StrictStr] = None
    tag_id: Optional[StrictStr] = Field(default=None, alias="tagID")
    tag_provider: Optional[StrictStr] = Field(default=None, alias="tagProvider")
    pass_type: Optional[StrictStr] = Field(default=None, alias="passType")
    pass_charge: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="passCharge")
    __properties: ClassVar[List[str]] = ["passIndex", "passID", "timestamp", "tagID", "tagProvider", "passType", "passCharge"]

    @field_validator('pass_type')
    def pass_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['home', 'visitor']):
            raise ValueError("must be one of enum values ('home', 'visitor')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TollStationPassesTollStationIDDateFromDateToGet200ResponsePassListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "passIndex": obj.get("passIndex"),
            "passID": obj.get("passID"),
            "timestamp": obj.get("timestamp"),
            "tagID": obj.get("tagID"),
            "tagProvider": obj.get("tagProvider"),
            "passType": obj.get("passType"),
            "passCharge": obj.get("passCharge")
        })
        return _obj


